spring:
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true #모든 네임스페이스에서 활성화
  redis:
    host: ${REDIS_HOST}
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/item_server
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
jwt:
  secretKey: mysecret
  token:
    recommend-expiration-time: 900000