kafka:
  bootstrapAddress: localhost:9092, localhost:9093
  admin:
    properties:
  topic:
    alarm:
      name: alarm
      replicationFactor: 2
      numPartitions: 2
  consumer:
    alarm:
      rdb-group-id: createAlarmInRDB
      redis-group-id: publishInRedis

    autoOffsetResetConfig: latest
  producer:
    acksConfig: all
    retry: 3
    enable-idempotence: true
    max-in-flight-requests-per-connection:
spring:
  kafka:
    producer:
      properties:
        min:
          insync:
            replicas: 2 # Kafka 클러스터에 대한 초기 연결에 사용할 호스트 : 포트 목록
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true #모든 네임스페이스에서 활성화
  redis:
    host: ${REDIS_HOST}
    port: 6379
  security:
    user:
      name: user
      password: password #PasswordEncoder.encode(password)
  application:
    name: order-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/order_server
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
jwt:
  expiration: 30 # 30 min
  secretKey: mysecret
pay:
  admin-key: ${ADMIN_KEY}
toss:
  toss-key: ${TOSS_KEY}