spring:
  kafka:
    bootstrap-servers:
      - b-2.democluster2.o89s59.c2.kafka.ap-northeast-2.amazonaws.com:9098
      - b-3.democluster2.o89s59.c2.kafka.ap-northeast-2.amazonaws.com:9098
      - b-1.democluster2.o89s59.c2.kafka.ap-northeast-2.amazonaws.com:9098
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true #모든 네임스페이스에서 활성화
  redis:
    host: ${REDIS_HOST}
    port: 6379
  security:
    user:
      name: user
      password: password #PasswordEncoder.encode(password)
  application:
    name: order-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/order_server
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
jwt:
  expiration: 30 # 30 min
  secretKey: mysecret
pay:
  admin-key: ${ADMIN_KEY}
toss:
  toss-key: ${TOSS_KEY}