spring:
  cloud :
    kubernetes:
      discovery:
        all-namespaces: true #모든 네임스페이스에서 활성화
  security:
    user:
      name: user
      password: password #PasswordEncoder.encode(password)
  application:
    name: member-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/member
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}         # 사용할 구글 이메일 주소 입력
    password: ${MAIL_PASSWORD}  # 생성된 구글 앱 비밀번호 입력
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
  redis:
    host: ${REDIS_HOST}
    port: 6379
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show_sql: true
jwt:
  secretKey: mysecret
  token:
    access-expiration-time: 1800000
    refresh-expiration-time: 604800000
