apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ortopia-gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ortopia-gateway
  template:
  # pod의 네임
    metadata:
      labels:
        app: ortopia-gateway
    spec:
      containers:
      - name: ortopia-gateway
        image: 168123310368.dkr.ecr.ap-northeast-2.amazonaws.com/ortopia_gateway:latest
        ports:
        - containerPort: 8080
        env:
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: ortopia-redis
                key: REDIS_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: ortopia-gateway-service
spec:
# ClusterIp는 클러스터 내부에서만 접근 가능한 service를 생성
  type: ClusterIP
  ports:
  - name : http
    port: 80
    targetPort: 8080
  selector:
    app: ortopia-gateway