server:
  port: 8080
spring:
#    유레카 서버에 아래 application name으로 서비스명을 등록.
  application:
    name: API-gateway
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true # 모든 네임스페이스에서 탐색
      loadbalancer:
        mode: service # loadbalancer 모드를 Kubernetes 서비스 이름 기반으로 설정
    gateway:
      routes:
        - id: item-service
          predicates:
            - Path=/item-service/**
          filters:
            - StripPrefix=1
          uri: lb://item-service
        - id: ortopia-member-service
          predicates:
            - Path=/ortopia-member-service/**
          filters:
            - StripPrefix=1
          uri: lb://ortopia-member-service
        - id: order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
          uri: lb://order-service
        - id: notice-service
          predicates:
            - Path=/notice-service/**
          filters:
            - StripPrefix=1
          uri: lb://notice-service
  redis:
    host: localhost
    port: 6379
jwt:
  expiration: 30 # 30 min
  secretKey: mysecret
  token:
    access-expiration-time: 1800000
